# Generated by Django 2.2 on 2020-02-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
